import * as fs from "fs";
import { StoragePaths } from "./paths";

/**
 * Builds the standalone Node.js script that Claude Code's `statusLine`
 * command actually executes. It has no npm dependencies (only Node core
 * modules) since it runs completely outside the extension host, invoked
 * directly by Claude Code as a subprocess on every status-line refresh.
 *
 * Responsibilities, in order:
 *  1. Read the JSON payload Claude Code pipes via stdin.
 *  2. Append it (with a receipt timestamp) to events.jsonl for the
 *     extension to pick up — this is the only line that matters for us.
 *  3. Print a short, human-readable line to stdout so the terminal status
 *     line still shows something useful even when VS Code isn't running.
 *
 * Must never throw past its top-level try/catch and must always exit
 * quickly — a hung or crashing script blanks Claude Code's status line.
 */
export function buildBridgeScriptSource(paths: StoragePaths): string {
  const eventsLogLiteral = JSON.stringify(paths.eventsLog);

  return `#!/usr/bin/env node
// Auto-generated by the "Claude Token Counter" VS Code extension.
// Safe to delete — the extension recreates it on next activation.
// Do not edit by hand; edits are overwritten on extension startup.
"use strict";

const fs = require("fs");
const path = require("path");

const EVENTS_LOG = ${eventsLogLiteral};

let input = "";
process.stdin.on("data", (chunk) => {
  input += chunk;
});

process.stdin.on("end", () => {
  let line = "";
  try {
    const payload = JSON.parse(input);
    const record = JSON.stringify({
      received_at: new Date().toISOString(),
      payload,
    });

    fs.mkdirSync(path.dirname(EVENTS_LOG), { recursive: true });
    fs.appendFileSync(EVENTS_LOG, record + "\\n");

    line = renderLine(payload);
  } catch (err) {
    // Never let a bad payload blank the status line or crash the caller.
    line = "[Claude Token Counter] (error reading usage)";
  }
  process.stdout.write(line + "\\n");
  process.exit(0);
});

// Also cap how long we wait on stdin — a wedged pipe should not hang
// Claude Code's status-line refresh forever.
setTimeout(() => {
  process.stdout.write("\\n");
  process.exit(0);
}, 2000).unref();

function renderLine(payload) {
  const model = payload && payload.model && payload.model.display_name;
  const cost = payload && payload.cost && payload.cost.total_cost_usd;
  const pct = payload && payload.context_window && payload.context_window.used_percentage;
  const parts = [];
  if (model) parts.push("[" + model + "]");
  if (typeof cost === "number") parts.push("$" + cost.toFixed(4));
  if (typeof pct === "number") parts.push(Math.round(pct) + "% ctx");
  return parts.length ? parts.join(" \\u00b7 ") : "[Claude Token Counter]";
}
`;
}

export function writeBridgeScript(paths: StoragePaths): void {
  fs.mkdirSync(paths.root, { recursive: true });
  fs.writeFileSync(paths.bridgeScript, buildBridgeScriptSource(paths), {
    mode: 0o755,
  });
}
